parameters:
  path: ''
  framework: ''

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet build -f ${{ parameters.framework }}
  inputs:
    command: build
    configuration: Release
    projects: ${{ parameters.path }}
    arguments: -f ${{ parameters.framework }}

- task: DotNetCoreCLI@2
  displayName: dotnet test -f ${{ parameters.framework }}
  inputs:
    command: test
    nobuild: true
    configuration: Release
    projects: ${{ parameters.path }}
    arguments: --logger trx -f ${{ parameters.framework }}
