parameters:
  path: ''
  framework: ''

steps:
- task: DotNetCoreCLI@2
  displayName: dotnet build -f ${{ parameters.framework }}
  inputs:
    command: build
    configuration: Release
    projects: ${{ parameters.path }}
