matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
    - os: osx # OSX 10.12
      osx_image: xcode8.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo ./scripts/ubuntu-prereqs.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./scripts/mac-prereqs.sh ; fi

install:
  - ./scripts/dotnet-install.sh
  - PATH=$PATH:$HOME/.dotnet && export PATH

script:
  - ./scripts/build-netcore.sh
  - ./scripts/test-netcore.sh
