language: csharp

matrix:
  include:
    - os: osx # OSX 10.11
      osx_image: xcode7.2

before_install:
  - brew update
  - brew install openssl
  - mkdir -p /usr/local/lib
  - ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/
  - ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/
  - curl -o "/tmp/dotnet.pkg" -fL https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-osx-x64.latest.pkg
  
install:
  - installer -pkg /tmp/dotnet.pkg -target /

before_script:
  - dotnet restore
  
script:
  - dotnet build -c Release -f netstandard1.4 src/msgpack.light/msgpack.light.csproj
  - dotnet build -c Release -f netcoreapp1.0 tests/msgpack.light.tests/msgpack.light.tests.csproj
  - dotnet test -c Release --noBuild tests/msgpack.light.tests/msgpack.light.tests.csproj