language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-rc3-004530
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      env: BUILD_DOCKER=true
    - os: osx # OSX 10.12
      osx_image: xcode7.3.1
  
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo sh ./scripts/osx-dotnet-install.sh ; fi

before_script:
  - if [[ "$BUILD_DOCKER" == false ]]; then dotnet restore ; fi

script:
  - if [[ "$BUILD_DOCKER" == false ]]; then ./scripts/build-netcore.sh ; fi
  - if [[ "$BUILD_DOCKER" == false ]]; then ./scripts/test-netcore.sh ; fi
  - if [[ "$BUILD_DOCKER" == true  ]]; then docker build . ; fi