language: csharp

matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
      dotnet: 1.0.0-preview4-004233
    - os: osx # OSX 10.11
      osx_image: xcode7.3.1
  
install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo ./scripts/osx-dotnet-install.sh ; fi

before_script:
  - dotnet restore

script:
  - dotnet build -c Release -f netstandard1.4 src/msgpack.light/msgpack.light.csproj
  - dotnet build -c Release -f netcoreapp1.0 tests/msgpack.light.tests/msgpack.light.tests.csproj
  - dotnet test -c Release --noBuild tests/msgpack.light.tests/msgpack.light.tests.csproj