matrix:
  include:
    - os: linux # Ubuntu 14.04
      dist: trusty
      sudo: required
    - os: linux # Ubuntu 14.04
      dist: trusty
      env: BUILD_DOCKER=true
    - os: osx # OSX 10.12
      osx_image: xcode8.2

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$BUILD_DOCKER" != true ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$BUILD_DOCKER" != true ]]; then sudo apt-get install -y jq libunwind8 libunwind8-dev gettext libicu-dev liblttng-ust-dev libcurl4-openssl-dev libssl-dev uuid-dev unzip ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openssl jq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link openssl --force ; fi

install:
  - if [[ "$BUILD_DOCKER" != true ]]; then ./scripts/dotnet-install.sh ; fi
  - if [[ "$BUILD_DOCKER" != true ]]; then PATH=$PATH:$HOME/.dotnet && export PATH ; fi

script:
  - if [[ "$BUILD_DOCKER" != true ]]; then ./scripts/build-netcore.sh ; fi
  - if [[ "$BUILD_DOCKER" != true ]]; then ./scripts/test-netcore.sh ; fi
  - if [[ "$BUILD_DOCKER" == true  ]]; then docker build . ; fi