version: 0.0.{build}
skip_tags: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

nuget:
  disable_publish_on_pr: true

configuration:
  - Debug
  - Release

matrix:
  fast_finish: false

init:
  - git config --global core.autocrlf true

install:
  - ps: nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
  - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  - ps: dnvm update-self
  - ps: dnvm upgrade
  - ps: dnvm install 1.0.0-rc1-update1
  - ps: dnvm list
  - ps: dnvm use 1.0.0-rc1-update1

before_build:
  - ps: dnu restore

build:
  parallel: true
  project: msgpack.sln
  verbosity: minimal

test_script:
  - ps: dnx -p tests/msgpack.tests test

deploy:
  provider: NuGet
  api_key:
    secure: GTa4jzXX3HvIl2acx6G8zZKJ5Tc8q4AM4SX+6mLtYMpnwkI3YmtrxOuGNteLuxsO
  skip_symbols: true
  artifact: /.*\.nupkg/

