jobs:
- job: macOsBuild
  pool:
    name: Hosted macOS
  steps:
    - template: .azure.build.yml

- job: macOsTest
  dependsOn:
  - macOsBuild
  pool:
    name: Hosted macOS
  steps:
    - template: .azure.test.yml

- job: linuxBuild
  pool:
    name: Hosted Ubuntu 1604
  steps:
    - template: .azure.build.yml

- job: linuxTest
  dependsOn:
  - linuxBuild
  pool:
    name: Hosted Ubuntu 1604
  steps:
    - template: .azure.test.yml

- job: winBuild
  pool:
    name: Hosted VS2017
  steps:
    - template: .azure.build.yml
      parameters:
        fullNet: true

- job: winTest
  dependsOn:
  - winBuild
  pool:
    name: Hosted VS2017
  steps:
    - template: .azure.test.yml
      parameters:
        fullNet: true