jobs:
- template: .azure.build.yml
  parameters:
    name: macOS
    pool: Hosted macOS

- template: .azure.build.yml
  parameters:
    name: Linux
    pool: Hosted Ubuntu 1604

- template: .azure.build.yml
  parameters:
    name: Windows
    pool: Hosted VS2017

# - template: .azure.test.yml
#   parameters:
#     name: macOS
#     pool: Hosted macOS

# - template: .azure.test.yml
#   parameters:
#     name: Linux
#     pool: Hosted Ubuntu 1604

# - template: .azure.test.yml
#   parameters:
#     name: Windows
#     pool: Hosted VS2017
