jobs:
- job: macOsBuild
  pool:
    name: Hosted macOS
  steps:
    - template: .azure/builds.yml

- job: macOsTest
  dependsOn:
  - macOsBuild
  pool:
    name: Hosted macOS
  steps:
    - template: .azure/tests.yml

- job: linuxBuild
  pool:
    name: Hosted Ubuntu 1604
  steps:
    - template: .azure/builds.yml

- job: linuxTest
  dependsOn:
  - linuxBuild
  pool:
    name: Hosted Ubuntu 1604
  steps:
    - script: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -channel 1.0 --runtime dotnet
    - script: curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin -channel 1.1 --runtime dotnet
    - template: .azure/tests.yml
      parameters:
        netcore1Global: false

- job: winBuild
  pool:
    name: Hosted VS2017
  steps:
    - template: .azure/builds.yml
      parameters:
        fullNet: true

- job: winTest
  dependsOn:
  - winBuild
  pool:
    name: Hosted VS2017
  steps:
    - template: .azure/tests.yml
      parameters:
        fullNet: true