jobs:
- template: .azure.build.yml
  parameters:
    name: macOS
    pool:
      vmImage: 'macOS 10.13'

- template: .azure.build.yml
  parameters:
    name: Linux
    pool:
      vmImage: 'Ubuntu 16.04'

- template: .azure.build.yml
  parameters:
    name: Windows
    pool:
      vmImage: 'vs2017-win2016'

- template: .azure.test.yml
  parameters:
    name: macOS
    pool:
      vmImage: 'macOS 10.13'

- template: .azure.test.yml
  parameters:
    name: Linux
    pool:
      vmImage: 'Ubuntu 16.04'

- template: .azure.test.yml
  parameters:
    name: Windows
    pool:
      vmImage: 'vs2017-win2016'
