parameters:
  path: ''
  framework: ''

steps:
- template: parameter.yml
  parameters:
    name: path
    value: ${{ parameters.path }}
- template: parameter.yml
  parameters:
    name: framework
    value: ${{ parameters.framework }}
- task: DotNetCoreCLI@2
  displayName: dotnet build -f ${{ parameters.framework }}
  inputs:
    command: build
    configuration: Release
    projects: ${{ parameters.path }}
    arguments: -f ${{ parameters.framework }}
